# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Test' do

# develop mode
pod 'EMSpeed/Core', :path => '../../'
pod 'EMSpeed/UI', :path => '../../'

# normal mode
#pod 'EMSpeed/Core', :podspec =>'../../EMSpeed.podspec'

end

